Validate docs

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -4,12 +4,32 @@ on: [push, pull_request]
 
 jobs:
 
+  validate-docs:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2.3.3
+      - name: Validate Documentation
+        run: |
+          dirname -- $(grep -Rl 'deprecated: "true"' compose/) | xargs rm -rf
+          for image in $(ls compose/.apps/); do
+              if ! ls -d docs/apps/* | grep -q "docs/apps/$image.md"; then
+                  echo "Missing documentation for $image"
+                  exit
+              fi
+              if ! grep -q "apps/$image.md" mkdocs.yml; then
+                  echo "Missing link for $image"
+                  exit
+              fi
+          done
+
   validate-images:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2.3.3
       - name: Validate Images
-        working-directory: compose
         run: |
-          dirname -- $(grep -Rl 'deprecated: "true"') | xargs rm -rf
-          for image in $(grep -RPoh "image: \K.*" | sort -u | grep -v '${'); do echo "Image: $image" && DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $image; done
+          dirname -- $(grep -Rl 'deprecated: "true"' compose/) | xargs rm -rf
+          for image in $(grep -RPoh "image: \K.*" | sort -u | grep -v '${'); do
+              echo "Image: $image"
+              DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $image
+          done
